// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO82YvQOiqjFGIbYvViNVukY0fLqYVcOI',
    appId: '1:243628967618:web:9ed02ba0b59432e90d9d5b',
    messagingSenderId: '243628967618',
    projectId: 'bestbakes-f1331',
    authDomain: 'bestbakes-f1331.firebaseapp.com',
    storageBucket: 'bestbakes-f1331.firebasestorage.app',
    measurementId: 'G-HE2BNPYVDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa-CFB_kCiNVdxiqau-f5S0aWoFOdpK4w',
    appId: '1:243628967618:android:a9258d9f1955a06e0d9d5b',
    messagingSenderId: '243628967618',
    projectId: 'bestbakes-f1331',
    storageBucket: 'bestbakes-f1331.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAceeYQK9bA9QYJ-i4dgYn3IMjtERQsJ4k',
    appId: '1:243628967618:ios:01c59960488170f70d9d5b',
    messagingSenderId: '243628967618',
    projectId: 'bestbakes-f1331',
    storageBucket: 'bestbakes-f1331.firebasestorage.app',
    iosBundleId: 'com.example.bestBakes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAceeYQK9bA9QYJ-i4dgYn3IMjtERQsJ4k',
    appId: '1:243628967618:ios:01c59960488170f70d9d5b',
    messagingSenderId: '243628967618',
    projectId: 'bestbakes-f1331',
    storageBucket: 'bestbakes-f1331.firebasestorage.app',
    iosBundleId: 'com.example.bestBakes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBO82YvQOiqjFGIbYvViNVukY0fLqYVcOI',
    appId: '1:243628967618:web:7759c4785b361f850d9d5b',
    messagingSenderId: '243628967618',
    projectId: 'bestbakes-f1331',
    authDomain: 'bestbakes-f1331.firebaseapp.com',
    storageBucket: 'bestbakes-f1331.firebasestorage.app',
    measurementId: 'G-EKV6D90KLZ',
  );
}
